// <auto-generated />
using Magneto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Magneto.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210614204538_DNAHashToDB")]
    partial class DNAHashToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Magneto.Models.Mutant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DNA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNAHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMutant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DNAHash")
                        .IsUnique()
                        .HasFilter("[DNAHash] IS NOT NULL");

                    b.ToTable("Mutants");
                });
#pragma warning restore 612, 618
        }
    }
}
